---
# Playbook for buddy-task
-
  hosts: aws
  user: ubuntu
  vars_files:
    - ./vault.yaml
  tasks:

  # 1. Creating directory

    - name: Check if directory exists
      stat:
        path: /home/ubuntu/new-dir
      register: result

    - name: Warn if exists
      debug:
        msg: "new-dir already exists, deleting"
      when: result.stat.exists == true

    - name: Delete directory if exists
      file:
        state: absent
        path: /home/ubuntu/new-dir
      when: result.stat.exists == true
    
    - name: Check if directory exists
      stat:
        path: /home/ubuntu/new-dir
      register: result
      when: result.stat.exists == true

    - name: Create new directory
      file:
        path: /home/ubuntu/new-dir
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
      when: result.stat.exists == false

    # 2. Create file with contents from variables

    - name: Create file with content from vars
      copy:
        content: "{{ text }}"
        dest: "/home/ubuntu/new-dir/new-file.txt"

    # 3. Create several files from seperate jinja templates

    - name: Create several files using loop and jinja templates
      template:
        src: "./jinja/{{ item.src }}"
        dest: "/home/ubuntu/new-dir/{{ item.dest }}"
      loop:
        - { src: "Monday.txt.j2", dest: "Monday.txt" }
        - { src: "Tuesday.txt.j2", dest: "Tuesday.txt" }
        - { src: "Wednesday.txt.j2", dest: "Wednesday.txt" }
